import { useState } from 'react';
import dueDiligenceLibrary from '@/data/r2_r3/due-diligence-library.json';
import policyLibrary from '@/data/r2_r3/policy-library.json';
import publicEvidence from '@/data/r2_r3/public-evidence.json';
import UploadWorkspace from '@/components/upload-workspace';
import RiskWorkbench from '@/components/risk-workbench';
import ComplianceLibrary from '@/components/compliance-library';
import SessionBadge from '@/components/session-badge';

const counts = {
  R2: { policies: policyLibrary.filter(x=>x.riskDomains.includes('R2')).length, evidence:publicEvidence.filter(x=>x.riskDomain==='R2').length, questions:dueDiligenceLibrary.filter(x=>x.riskDomain==='R2').length },
  R3: { policies: policyLibrary.filter(x=>x.riskDomains.includes('R3')).length, evidence:publicEvidence.filter(x=>x.riskDomain==='R3').length, questions:dueDiligenceLibrary.filter(x=>x.riskDomain==='R3').length },
};

function Login({onLogin}:{onLogin:()=>void}) {
  const [account,setAccount]=useState('expert-judge'); const [code,setCode]=useState(''); const [error,setError]=useState('');
  async function submit(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({account,accessCode:code})});if(!r.ok){setError((await r.json()).error);return;}onLogin();}
  return <main className="local-login"><section className="local-login-brand"><div className="login-logo">Z</div><h1>智险可控</h1><h2>人工智能科创企业全生命周期<br/>风险识别与智能治理 Agent</h2><p>面向科技金融人员与科创企业，以材料、证据、风险、尽调、治理和人工复核形成可追溯工作流。</p></section><section className="local-login-card"><p className="eyebrow">专家评审入口</p><h2>进入风险治理工作台</h2><form onSubmit={submit}><label>专家账号</label><input value={account} onChange={e=>setAccount(e.target.value)}/><label>比赛访问码</label><input type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="请输入专属访问码"/>{error&&<p className="local-login-error">{error}</p>}<button>验证并进入系统 →</button></form><p className="local-mode">国内演示版：材料解析与规则识别在当前浏览器完成，上传材料不传至境外服务。访问控制用于比赛演示，不用于生产系统。</p></section></main>;
}

function Dashboard(){return <main className="app-shell"><header className="topbar"><div className="brand-mark">Z</div><div className="brand-copy"><strong>平安科创智控 Agent</strong><span>人工智能科创企业风险治理工作台</span></div><div className="topbar-meta"><span className="demo-badge">国内比赛演示环境</span><SessionBadge displayName="专家评委" organization="比赛专家评审组" role="比赛专家／超级管理员"/></div></header><div className="workspace"><aside className="sidebar"><nav aria-label="主导航"><a className="active" href="#overview"><span>01</span>企业工作台</a><a href="#upload"><span>02</span>资料中心</a><a href="#risks"><span>03</span>风险诊断</a><a href="#transmission"><span>04</span>风险传导</a><a href="#evidence"><span>05</span>证据与AI复核</a><a href="#tasks"><span>06</span>尽调任务</a><a href="#views"><span>07</span>机构视图</a><a href="#reduction"><span>08</span>风险减量</a><a href="#audit"><span>09</span>复核审计</a><a href="#library"><span>10</span>规则资料库</a></nav><div className="data-scope"><p>研究数据底座</p><strong>12 家企业</strong><span>216 个指标观测单元</span><span>36 条风险记录</span></div></aside><section className="content" id="overview"><div className="domestic-notice">国内独立演示版｜文件在浏览器本地解析，规则与知识库辅助初筛，关键结论由人工复核。</div><div className="page-heading"><div><p className="eyebrow">科技金融风险治理</p><h1>企业风险治理中心</h1><div className="company-meta"><span>12家样本企业</span><span>R1—R5统一口径</span><span>材料—证据—尽调—复核闭环</span></div></div><div className="heading-actions"><a className="secondary-button" href="#materials">材料目录</a><a className="primary-button" href="#upload">＋ 上传新材料</a></div></div><section className="guardrail"><span>证据边界</span><p>材料原文、事实状态、风险解释和金融决策分层表达；证据不足时保留“需核验”</p><strong>不输出综合评分</strong></section><section className="supplement-strip"><div><span className="supplement-code">R2</span><p><strong>数据安全与合规资料库</strong><small>{counts.R2.policies}条权威规则 · {counts.R2.evidence}条公开披露 · {counts.R2.questions}项尽调问题</small></p></div><div><span className="supplement-code orange">R3</span><p><strong>知识产权与科技伦理资料库</strong><small>{counts.R3.policies}条权威规则 · {counts.R3.evidence}条公开披露 · {counts.R3.questions}项尽调问题</small></p></div><span className="review-note">企业自述 ≠ 控制有效<br/>重大结论必须人工复核</span></section><UploadWorkspace role="比赛专家／超级管理员" companyScope=""/><RiskWorkbench role="比赛专家／超级管理员" companyScope=""/><ComplianceLibrary/></section><aside className="agent-panel"><div className="agent-heading"><div className="agent-orb">AI</div><div><strong>智能风险治理 Agent</strong><span>证据优先 · 人工确认</span></div></div><div className="agent-message"><p>请选择材料和风险域，逐项定位证据、生成尽调任务并提交人工复核。</p></div><div className="agent-actions"><a href="#evidence"><span>01</span>定位原始证据</a><a href="#library"><span>02</span>查询规则与知识库</a><a href="#transmission"><span>03</span>查看风险传导</a><a href="#reduction"><span>04</span>制定风险减量</a><a href="#tasks"><span>05</span>生成尽调清单</a><a href="#audit"><span>06</span>提交人工复核</a></div><div className="agent-footer"><strong>处理原则</strong><p>材料提取 → 规则校验 → 人工确认</p><p>未知信息不补全，重大结论不自动发布。</p></div></aside></div></main>}

export default function App(){const [logged,setLogged]=useState(()=>localStorage.getItem('zhixian-session')==='1');return logged?<Dashboard/>:<Login onLogin={()=>setLogged(true)}/>}
